### ISSUE TITLE
Improve resilience: continue on refresh failure if token is still valid

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/python-tokens#2]
Currently we fresh the token 20 minutes before it expires (https://github.com/zalando-stups/python-tokens/blob/master/tokens/__init__.py#L111). The refresh might fail, but the token is still valid.
"tokens.get(..)" should return the still valid token in this case (and log the refresh error).

**Comment by Jan-M** [comment]
This gets another +1, we just ran into lots of 400 bad request/client errors although there is time left

**Comment by hjacobs** [comment]
:+1: from Frank

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/python-tokens/releases/tag/1.0.13
